# Generated by Django 5.1.2 on 2025-08-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TarefaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("concluido", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
